### ISSUE TITLE
item_git_deploy: KeyError('rev',)

### ISSUE THREAD

**Issue by rhazdon** [bundlewrap/plugins#2]
Hi, 

I got an error while deploying a git project with bw. 

Do you have any idea what happened there?

Bundlewrap Version: 2.2.0
plugins.json:

```
"item_git_deploy": {
        "files": {
            "items/git_deploy.py": "76c83f5fd14eba50e5494568d65fe3fe23a54a2b"
        },
        "version": 4
    },
```

items.py:

```
directories = {
    "/opt/ingxoxo": {},
}

git_deploy = {
    "/opt/ingxoxo": {
        'needs': ["directory:/opt/ingxoxo"],
        'repo': "ssh://git@github.com/ingxoxo/ingxoxo.git",
        'rev': "master",
    },
}
```

bw --debug apply my-server-1

```
[2016-03-07 14:40:49.610498] running on my-server-1: file -bh -- /opt/ingxoxo
[2016-03-07 14:40:49.631087] command finished with return code 0
[2016-03-07 14:40:49.636419] running 'git clone --bare --depth 1 --no-single-branch ssh://git@github.com/ingxoxo/ingxoxo.git .' in /var/folders/3x/v8jt65l930b3jj73kzfr8wzh0000gn/T/tmp5pky4hft
[2016-03-07 14:40:49.692582] command finished with return code 0
[2016-03-07 14:40:49.693991] stat for '/var/run/uwsgi' on my-server-1: {'mode': '0755', 'group': 'www-data', 'size': 80, 'owner': 'www-data'}
[2016-03-07 14:40:49.885806] command finished with return code 0
[2016-03-07 14:40:49.887084] stat for '/var/log/ingxoxo' on my-server-1: {'mode': '0755', 'group': 'www-data', 'size': 4096, 'owner': 'www-data'}
[2016-03-07 14:40:49.940193] command finished with return code 0
[2016-03-07 14:40:49.942752] running on my-server-1: stat -c '%U:%G:%a:%s' -- /opt/ingxoxo
[2016-03-07 14:40:50.273196] command finished with return code 0
[2016-03-07 14:40:50.274519] stat for '/opt/ingxoxo' on my-server-1: {'mode': '0755', 'group': 'root', 'size': 4096, 'owner': 'root'}
[2016-03-07 14:40:52.278378] registering /var/folders/3x/v8jt65l930b3jj73kzfr8wzh0000gn/T/tmp5pky4hft for deletion on exit
[2016-03-07 14:40:52.279229] running 'git rev-parse master' in /var/folders/3x/v8jt65l930b3jj73kzfr8wzh0000gn/T/tmp5pky4hft
[2016-03-07 14:40:52.284016] running on my-server-1: cat /opt/ingxoxo/.bundlewrap_git_deploy
[2016-03-07 14:40:52.628494] command finished with return code 1
[2016-03-07 14:40:52.645713] running on my-server-1: rm -R /tmp/bundlewrap.lock
[2016-03-07 14:40:52.955024] command finished with return code 0
[2016-03-07 14:40:52.966715] Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/concurrency.py", line 48, in _worker_process
    return_value = target(*msg['args'], **msg['kwargs'])
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/node.py", line 475, in apply
    profiling=profiling,
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/node.py", line 130, in apply_items
    item, skipped_items = item_queue.pop()
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/itemqueue.py", line 96, in pop
    if item._precedes_incorrect_item(interactive=interactive):
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/items/__init__.py", line 234, in _precedes_incorrect_item
    if item._precedes_incorrect_item():
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/items/__init__.py", line 245, in _precedes_incorrect_item
    return not self.cached_status.correct
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/utils/__init__.py", line 39, in cache_wrapper
    return_value = prop(self)
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/items/__init__.py", line 218, in cached_status
    return self.get_status()
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/items/__init__.py", line 493, in get_status
    return ItemStatus(self.cached_cdict, self.cached_sdict)
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/items/__init__.py", line 60, in __init__
    self.keys_to_fix = diff_keys(cdict, sdict)
  File "/usr/local/lib/python3.5/site-packages/bundlewrap/utils/statedict.py", line 38, in diff_keys
    if value != sdict2[key]:
KeyError: 'rev'

[2016-03-07 14:40:52.967237] my-server-1: ! KeyError('rev',)
```

**Comment by trehn** [comment]
Thanks for the report. I just pushed an update for the git_deploy plugin, please reopen if that doesn't fix it.

`bw repo plugin update`

**Comment by rhazdon** [comment]
Great! Thank you, it works fine!
